---
name: dockerhub-semantic-release
description: Utilize semantic-release and publish images to docker hub automatically
branding:
  color: orange
  icon: rotate-ccw

inputs:
  image:
    description: Image slug containting org and image (e.g. user/imagename)
    required: true
    default: null
  dockerhub_username:
    description: Username for docker hub
    required: true
    default: null
  dockerhub_token:
    description: Token for docker hub
    required: true
    default: null
  github_token:
    description: Github token to use
    required: true
    default: null
  platforms:
    description: List of target platforms for build (as specified by docker/build-push-action)
    required: false
    default: null

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run semantic-release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 24.0.0
        extra_plugins: |
          @semantic-release/git@10.0.1
          @semantic-release/changelog@6.0.3
          conventional-changelog-conventionalcommits@8.0.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Setup Docker buildx
      if: steps.semantic-release.outputs.new_release_published == 'true'
      uses: docker/setup-buildx-action@v3
    - name: Login to dockerhub
      if: steps.semantic-release.outputs.new_release_published == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4.0.0
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
        repository: ${{ inputs.image }}
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
    - name: Build and push image
      if: steps.semantic-release.outputs.new_release_published == 'true'
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ inputs.image }}:latest, ${{ inputs.image }}:${{ steps.semantic-release.outputs.new_release_version }}
